# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project\MyProjects\Python\rep\new_report_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 536)
        Form.setMinimumSize(QtCore.QSize(576, 536))
        Form.setMaximumSize(QtCore.QSize(576, 536))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(9, 136, 555, 391))
        self.groupBox_3.setMinimumSize(QtCore.QSize(555, 391))
        self.groupBox_3.setMaximumSize(QtCore.QSize(0, 391))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 511, 301))
        self.tableWidget.setMinimumSize(QtCore.QSize(511, 301))
        self.tableWidget.setMaximumSize(QtCore.QSize(511, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.addDocBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.addDocBtn.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.addDocBtn.setObjectName("addDocBtn")
        self.delDocBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.delDocBtn.setGeometry(QtCore.QRect(110, 30, 75, 23))
        self.delDocBtn.setObjectName("delDocBtn")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(206, 30, 247, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(125, 20))
        self.label_5.setMaximumSize(QtCore.QSize(125, 20))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.docsCountTb = QtWidgets.QLineEdit(self.layoutWidget)
        self.docsCountTb.setMinimumSize(QtCore.QSize(25, 20))
        self.docsCountTb.setMaximumSize(QtCore.QSize(25, 20))
        self.docsCountTb.setObjectName("docsCountTb")
        self.horizontalLayout_5.addWidget(self.docsCountTb)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(20, 20))
        self.label_6.setMaximumSize(QtCore.QSize(20, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.sheetsCountTb = QtWidgets.QLineEdit(self.layoutWidget)
        self.sheetsCountTb.setMinimumSize(QtCore.QSize(25, 20))
        self.sheetsCountTb.setMaximumSize(QtCore.QSize(25, 20))
        self.sheetsCountTb.setObjectName("sheetsCountTb")
        self.horizontalLayout_5.addWidget(self.sheetsCountTb)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(40, 0))
        self.label_7.setMaximumSize(QtCore.QSize(40, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(9, 9, 70, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.exitEditorBtn = QtWidgets.QPushButton(self.widget)
        self.exitEditorBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.exitEditorBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.exitEditorBtn.setStyleSheet("background-color: rgb(255, 57, 57);")
        self.exitEditorBtn.setObjectName("exitEditorBtn")
        self.horizontalLayout_4.addWidget(self.exitEditorBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.maxEditorBtn = QtWidgets.QPushButton(self.widget)
        self.maxEditorBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.maxEditorBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.maxEditorBtn.setObjectName("maxEditorBtn")
        self.horizontalLayout_4.addWidget(self.maxEditorBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.minEditorBtn = QtWidgets.QPushButton(self.widget)
        self.minEditorBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.minEditorBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.minEditorBtn.setStyleSheet("")
        self.minEditorBtn.setObjectName("minEditorBtn")
        self.horizontalLayout_4.addWidget(self.minEditorBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_4.setStretch(0, 20)
        self.horizontalLayout_4.setStretch(2, 1000)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(191, 38, 151, 91))
        self.groupBox_2.setMinimumSize(QtCore.QSize(151, 61))
        self.groupBox_2.setMaximumSize(QtCore.QSize(151, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 30, 131, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rubCountTb = QtWidgets.QLineEdit(self.layoutWidget1)
        self.rubCountTb.setAlignment(QtCore.Qt.AlignCenter)
        self.rubCountTb.setObjectName("rubCountTb")
        self.horizontalLayout_2.addWidget(self.rubCountTb)
        self.kopCountTb = QtWidgets.QLineEdit(self.layoutWidget1)
        self.kopCountTb.setMinimumSize(QtCore.QSize(30, 20))
        self.kopCountTb.setMaximumSize(QtCore.QSize(30, 20))
        self.kopCountTb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.kopCountTb.setObjectName("kopCountTb")
        self.horizontalLayout_2.addWidget(self.kopCountTb)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(382, 38, 181, 91))
        self.groupBox_4.setMinimumSize(QtCore.QSize(181, 91))
        self.groupBox_4.setMaximumSize(QtCore.QSize(181, 91))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 30, 161, 20))
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(11, 61, 161, 20))
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 38, 141, 91))
        self.groupBox.setMinimumSize(QtCore.QSize(141, 61))
        self.groupBox.setMaximumSize(QtCore.QSize(141, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 121, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reportNumberTb = QtWidgets.QLineEdit(self.layoutWidget2)
        self.reportNumberTb.setMinimumSize(QtCore.QSize(30, 20))
        self.reportNumberTb.setMaximumSize(QtCore.QSize(30, 20))
        self.reportNumberTb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reportNumberTb.setAlignment(QtCore.Qt.AlignCenter)
        self.reportNumberTb.setObjectName("reportNumberTb")
        self.horizontalLayout.addWidget(self.reportNumberTb)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget2)
        self.dateEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dateEdit.setDate(QtCore.QDate(2019, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Отчет"))
        self.groupBox_3.setTitle(_translate("Form", "Документы"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "№"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Документ"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Номер "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Дата"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Сумма"))
        self.addDocBtn.setText(_translate("Form", "Добавить"))
        self.delDocBtn.setText(_translate("Form", "Удалить"))
        self.label_5.setText(_translate("Form", "Количество документов"))
        self.label_6.setText(_translate("Form", "на"))
        self.label_7.setText(_translate("Form", "листах"))
        self.exitEditorBtn.setText(_translate("Form", "✖"))
        self.maxEditorBtn.setText(_translate("Form", "☐"))
        self.minEditorBtn.setText(_translate("Form", "_"))
        self.groupBox_2.setTitle(_translate("Form", "Отчет в сумме"))
        self.rubCountTb.setPlaceholderText(_translate("Form", "руб."))
        self.kopCountTb.setPlaceholderText(_translate("Form", "коп."))
        self.label.setText(_translate("Form", "₽"))
        self.groupBox_4.setTitle(_translate("Form", "Подотчетное лицо"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "ФИО"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "Должность"))
        self.groupBox.setTitle(_translate("Form", "Авансовый отчет"))
        self.reportNumberTb.setPlaceholderText(_translate("Form", "№"))

