# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project\MyProjects\Python\rep\start_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 361)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.exitBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.exitBtn.setStyleSheet("background-color: rgb(255, 57, 57);")
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_4.addWidget(self.exitBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.minBtn = QtWidgets.QPushButton(self.centralwidget)
        self.minBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.minBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.minBtn.setStyleSheet("")
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout_4.addWidget(self.minBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.signInBtn = QtWidgets.QPushButton(self.centralwidget)
        self.signInBtn.setMinimumSize(QtCore.QSize(60, 20))
        self.signInBtn.setMaximumSize(QtCore.QSize(60, 20))
        self.signInBtn.setObjectName("signInBtn")
        self.horizontalLayout_4.addWidget(self.signInBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_4.setStretch(0, 20)
        self.horizontalLayout_4.setStretch(1, 3000)
        self.horizontalLayout_4.setStretch(2, 300000)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.openBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openBtn.setMinimumSize(QtCore.QSize(30, 20))
        self.openBtn.setMaximumSize(QtCore.QSize(30, 20))
        self.openBtn.setObjectName("openBtn")
        self.horizontalLayout.addWidget(self.openBtn)
        self.newBtn = QtWidgets.QPushButton(self.centralwidget)
        self.newBtn.setMinimumSize(QtCore.QSize(75, 20))
        self.newBtn.setMaximumSize(QtCore.QSize(75, 20))
        self.newBtn.setObjectName("newBtn")
        self.horizontalLayout.addWidget(self.newBtn, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(531, 311))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Report Editor"))
        self.exitBtn.setText(_translate("MainWindow", "✖"))
        self.minBtn.setText(_translate("MainWindow", "_"))
        self.signInBtn.setText(_translate("MainWindow", "Войти"))
        self.openBtn.setText(_translate("MainWindow", "📂"))
        self.newBtn.setText(_translate("MainWindow", "Создать"))
        self.groupBox.setTitle(_translate("MainWindow", "Все отчёты"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№ отчёта"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Город"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Сумма"))

